# Project: Plugin
# Makefile created by Dev-C++ 5.6.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = plugin.o ../../../src/TuxStrings.o
LINKOBJ  = plugin.o ../../../src/TuxStrings.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc --no-export-all-symbols --add-stdcall-alias libTuxDroidServer.a
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"../../../include" -I"../../../include/win32" -I"../../../include/win32/pthread" -I"../../../include/win32/iconv"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++" -I"../../../include" -I"../../../include/win32" -I"../../../include/win32/pthread" -I"../../../include/win32/iconv"
BIN      = Plugin.dll
CXXFLAGS = $(CXXINCS) -DBUILDING_DLL=1
CFLAGS   = $(INCS) -DBUILDING_DLL=1
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

DLLWRAP   = dllwrap.exe
DEFFILE   = libPlugin.def
STATICLIB = libPlugin.a

$(BIN): $(LINKOBJ)
	$(DLLWRAP) --output-def $(DEFFILE) --implib $(STATICLIB) $(LINKOBJ) $(LIBS) -o $(BIN)

plugin.o: plugin.c
	$(CC) -c plugin.c -o plugin.o $(CFLAGS)

../../../src/TuxStrings.o: ../../../src/TuxStrings.c
	$(CC) -c ../../../src/TuxStrings.c -o ../../../src/TuxStrings.o $(CFLAGS)
